# # example netlify.toml
# [build]
#   command = "npm run build"  # Command to build the frontend
#   functions = "netlify/functions"  # Directory for Netlify Functions
#   publish = "build"  # Directory for frontend build output

# [functions]
#   external_node_modules = ["express", "serverless-http"]  # Include necessary modules
#   node_bundler = "esbuild"  # Use esbuild for bundling

# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/:splat"  # Redirect API requests to Netlify Functions
#   status = 200
#   force = true

# [dev]
#   command = "npm start" # Command to start your dev server
#   port = 8888 # Port that the dev server will be listening on
#   targetPort = 3000 # Port where Netlify Dev will serve both frontend and function
 
#   ## more info on configuring this file: https://ntl.fyi/file-based-build-config
[build]
  command = "npm run build"
  functions = "netlify/functions"  # Directory where your functions are stored
  publish = "build"                # Directory where your frontend is published

[functions]
  external_node_modules = ["express", "serverless-http"]  # Ensure these modules are bundled
  node_bundler = "esbuild"                                # Use esbuild for bundling

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"  # Redirect API requests to the serverless function
  status = 200